const countries: { iso3: string; name: string; flag: string }[] = [
  { iso3: "AFG", name: "Afghanistan", flag: "🇦🇫" },
  { iso3: "ALB", name: "Albania", flag: "🇦🇱" },
  { iso3: "DZA", name: "Algeria", flag: "🇩🇿" },
  { iso3: "ASM", name: "American Samoa", flag: "🇦🇸" },
  { iso3: "AND", name: "Andorra", flag: "🇦🇩" },
  { iso3: "AGO", name: "Angola", flag: "🇦🇴" },
  { iso3: "AIA", name: "Anguilla", flag: "🇦🇮" },
  { iso3: "ATA", name: "Antarctica", flag: "🇦🇶" },
  { iso3: "ATG", name: "Antigua and Barbuda", flag: "🇦🇬" },
  { iso3: "ARG", name: "Argentina", flag: "🇦🇷" },
  { iso3: "ARM", name: "Armenia", flag: "🇦🇲" },
  { iso3: "ABW", name: "Aruba", flag: "🇦🇼" },
  { iso3: "AUS", name: "Australia", flag: "🇦🇺" },
  { iso3: "AUT", name: "Austria", flag: "🇦🇹" },
  { iso3: "AZE", name: "Azerbaijan", flag: "🇦🇿" },
  { iso3: "BHS", name: "Bahamas", flag: "🇧🇸" },
  { iso3: "BHR", name: "Bahrain", flag: "🇧🇭" },
  { iso3: "BGD", name: "Bangladesh", flag: "🇧🇩" },
  { iso3: "BRB", name: "Barbados", flag: "🇧🇧" },
  { iso3: "BLR", name: "Belarus", flag: "🇧🇾" },
  { iso3: "BEL", name: "Belgium", flag: "🇧🇪" },
  { iso3: "BLZ", name: "Belize", flag: "🇧🇿" },
  { iso3: "BEN", name: "Benin", flag: "🇧🇯" },
  { iso3: "BMU", name: "Bermuda", flag: "🇧🇲" },
  { iso3: "BTN", name: "Bhutan", flag: "🇧🇹" },
  { iso3: "BOL", name: "Bolivia (Plurinational State of)", flag: "🇧🇴" },
  { iso3: "BES", name: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶" },
  { iso3: "BIH", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { iso3: "BWA", name: "Botswana", flag: "🇧🇼" },
  { iso3: "BVT", name: "Bouvet Island", flag: "🇧🇻" },
  { iso3: "BRA", name: "Brazil", flag: "🇧🇷" },
  { iso3: "IOT", name: "British Indian Ocean Territory", flag: "🇮🇴" },
  { iso3: "BRN", name: "Brunei Darussalam", flag: "🇧🇳" },
  { iso3: "BGR", name: "Bulgaria", flag: "🇧🇬" },
  { iso3: "BFA", name: "Burkina Faso", flag: "🇧🇫" },
  { iso3: "BDI", name: "Burundi", flag: "🇧🇮" },
  { iso3: "CPV", name: "Cabo Verde", flag: "🇨🇻" },
  { iso3: "KHM", name: "Cambodia", flag: "🇰🇭" },
  { iso3: "CMR", name: "Cameroon", flag: "🇨🇲" },
  { iso3: "CAN", name: "Canada", flag: "🇨🇦" },
  { iso3: "CYM", name: "Cayman Islands", flag: "🇰🇾" },
  { iso3: "CAF", name: "Central African Republic", flag: "🇨🇫" },
  { iso3: "TCD", name: "Chad", flag: "🇹🇩" },
  { iso3: "CHL", name: "Chile", flag: "🇨🇱" },
  { iso3: "CHN", name: "China", flag: "🇨🇳" },
  { iso3: "CXR", name: "Christmas Island", flag: "🇨🇽" },
  { iso3: "CCK", name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { iso3: "COL", name: "Colombia", flag: "🇨🇴" },
  { iso3: "COM", name: "Comoros", flag: "🇰🇲" },
  { iso3: "COD", name: "Congo (Democratic Republic of the)", flag: "🇨🇩" },
  { iso3: "COG", name: "Congo", flag: "🇨🇬" },
  { iso3: "COK", name: "Cook Islands", flag: "🇨🇰" },
  { iso3: "CRI", name: "Costa Rica", flag: "🇨🇷" },
  { iso3: "HRV", name: "Croatia", flag: "🇭🇷" },
  { iso3: "CUB", name: "Cuba", flag: "🇨🇺" },
  { iso3: "CUW", name: "Curaçao", flag: "🇨🇼" },
  { iso3: "CYP", name: "Cyprus", flag: "🇨🇾" },
  { iso3: "CZE", name: "Czechia", flag: "🇨🇿" },
  { iso3: "CIV", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { iso3: "DNK", name: "Denmark", flag: "🇩🇰" },
  { iso3: "DJI", name: "Djibouti", flag: "🇩🇯" },
  { iso3: "DMA", name: "Dominica", flag: "🇩🇲" },
  { iso3: "DOM", name: "Dominican Republic", flag: "🇩🇴" },
  { iso3: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { iso3: "EGY", name: "Egypt", flag: "🇪🇬" },
  { iso3: "SLV", name: "El Salvador", flag: "🇸🇻" },
  { iso3: "GNQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { iso3: "ERI", name: "Eritrea", flag: "🇪🇷" },
  { iso3: "EST", name: "Estonia", flag: "🇪🇪" },
  { iso3: "SWZ", name: "Eswatini", flag: "🇸🇿" },
  { iso3: "ETH", name: "Ethiopia", flag: "🇪🇹" },
  { iso3: "FLK", name: "Falkland Islands (Malvinas)", flag: "🇫🇰" },
  { iso3: "FRO", name: "Faroe Islands", flag: "🇫🇴" },
  { iso3: "FJI", name: "Fiji", flag: "🇫🇯" },
  { iso3: "FIN", name: "Finland", flag: "🇫🇮" },
  { iso3: "FRA", name: "France", flag: "🇫🇷" },
  { iso3: "GUF", name: "French Guiana", flag: "🇬🇫" },
  { iso3: "PYF", name: "French Polynesia", flag: "🇵🇫" },
  { iso3: "ATF", name: "French Southern Territories", flag: "🇹🇫" },
  { iso3: "GAB", name: "Gabon", flag: "🇬🇦" },
  { iso3: "GMB", name: "Gambia", flag: "🇬🇲" },
  { iso3: "GEO", name: "Georgia", flag: "🇬🇪" },
  { iso3: "DEU", name: "Germany", flag: "🇩🇪" },
  { iso3: "GHA", name: "Ghana", flag: "🇬🇭" },
  { iso3: "GIB", name: "Gibraltar", flag: "🇬🇮" },
  { iso3: "GRC", name: "Greece", flag: "🇬🇷" },
  { iso3: "GRL", name: "Greenland", flag: "🇬🇱" },
  { iso3: "GRD", name: "Grenada", flag: "🇬🇩" },
  { iso3: "GLP", name: "Guadeloupe", flag: "🇬🇵" },
  { iso3: "GUM", name: "Guam", flag: "🇬🇺" },
  { iso3: "GTM", name: "Guatemala", flag: "🇬🇹" },
  { iso3: "GGY", name: "Guernsey", flag: "🇬🇬" },
  { iso3: "GIN", name: "Guinea", flag: "🇬🇳" },
  { iso3: "GNB", name: "Guinea-Bissau", flag: "🇬🇼" },
  { iso3: "GUY", name: "Guyana", flag: "🇬🇾" },
  { iso3: "HTI", name: "Haiti", flag: "🇭🇹" },
  { iso3: "HMD", name: "Heard Island and McDonald Islands", flag: "🇭🇲" },
  { iso3: "VAT", name: "Holy See", flag: "🇻🇦" },
  { iso3: "HND", name: "Honduras", flag: "🇭🇳" },
  { iso3: "HKG", name: "Hong Kong", flag: "🇭🇰" },
  { iso3: "HUN", name: "Hungary", flag: "🇭🇺" },
  { iso3: "ISL", name: "Iceland", flag: "🇮🇸" },
  { iso3: "IND", name: "India", flag: "🇮🇳" },
  { iso3: "IDN", name: "Indonesia", flag: "🇮🇩" },
  { iso3: "IRN", name: "Iran (Islamic Republic of)", flag: "🇮🇷" },
  { iso3: "IRQ", name: "Iraq", flag: "🇮🇶" },
  { iso3: "IRL", name: "Ireland", flag: "🇮🇪" },
  { iso3: "IMN", name: "Isle of Man", flag: "🇮🇲" },
  { iso3: "ISR", name: "Israel", flag: "🇮🇱" },
  { iso3: "ITA", name: "Italy", flag: "🇮🇹" },
  { iso3: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { iso3: "JPN", name: "Japan", flag: "🇯🇵" },
  { iso3: "JEY", name: "Jersey", flag: "🇯🇪" },
  { iso3: "JOR", name: "Jordan", flag: "🇯🇴" },
  { iso3: "KAZ", name: "Kazakhstan", flag: "🇰🇿" },
  { iso3: "KEN", name: "Kenya", flag: "🇰🇪" },
  { iso3: "KIR", name: "Kiribati", flag: "🇰🇮" },
  { iso3: "PRK", name: "Korea (Democratic People's Republic of)", flag: "🇰🇵" },
  { iso3: "KOR", name: "Korea (Republic of)", flag: "🇰🇷" },
  { iso3: "KWT", name: "Kuwait", flag: "🇰🇼" },
  { iso3: "KGZ", name: "Kyrgyzstan", flag: "🇰🇬" },
  { iso3: "LAO", name: "Lao People's Democratic Republic", flag: "🇱🇦" },
  { iso3: "LVA", name: "Latvia", flag: "🇱🇻" },
  { iso3: "LBN", name: "Lebanon", flag: "🇱🇧" },
  { iso3: "LSO", name: "Lesotho", flag: "🇱🇸" },
  { iso3: "LBR", name: "Liberia", flag: "🇱🇷" },
  { iso3: "LBY", name: "Libya", flag: "🇱🇾" },
  { iso3: "LIE", name: "Liechtenstein", flag: "🇱🇮" },
  { iso3: "LTU", name: "Lithuania", flag: "🇱🇹" },
  { iso3: "LUX", name: "Luxembourg", flag: "🇱🇺" },
  { iso3: "MAC", name: "Macao", flag: "🇲🇴" },
  { iso3: "MDG", name: "Madagascar", flag: "🇲🇬" },
  { iso3: "MWI", name: "Malawi", flag: "🇲🇼" },
  { iso3: "MYS", name: "Malaysia", flag: "🇲🇾" },
  { iso3: "MDV", name: "Maldives", flag: "🇲🇻" },
  { iso3: "MLI", name: "Mali", flag: "🇲🇱" },
  { iso3: "MLT", name: "Malta", flag: "🇲🇹" },
  { iso3: "MHL", name: "Marshall Islands", flag: "🇲🇭" },
  { iso3: "MTQ", name: "Martinique", flag: "🇲🇶" },
  { iso3: "MRT", name: "Mauritania", flag: "🇲🇷" },
  { iso3: "MUS", name: "Mauritius", flag: "🇲🇺" },
  { iso3: "MYT", name: "Mayotte", flag: "🇾🇹" },
  { iso3: "MEX", name: "Mexico", flag: "🇲🇽" },
  { iso3: "FSM", name: "Micronesia (Federated States of)", flag: "🇫🇲" },
  { iso3: "MDA", name: "Moldova (Republic of)", flag: "🇲🇩" },
  { iso3: "MCO", name: "Monaco", flag: "🇲🇨" },
  { iso3: "MNG", name: "Mongolia", flag: "🇲🇳" },
  { iso3: "MNE", name: "Montenegro", flag: "🇲🇪" },
  { iso3: "MSR", name: "Montserrat", flag: "🇲🇸" },
  { iso3: "MAR", name: "Morocco", flag: "🇲🇦" },
  { iso3: "MOZ", name: "Mozambique", flag: "🇲🇿" },
  { iso3: "MMR", name: "Myanmar", flag: "🇲🇲" },
  { iso3: "NAM", name: "Namibia", flag: "🇳🇦" },
  { iso3: "NRU", name: "Nauru", flag: "🇳🇷" },
  { iso3: "NPL", name: "Nepal", flag: "🇳🇵" },
  { iso3: "NLD", name: "Netherlands", flag: "🇳🇱" },
  { iso3: "NCL", name: "New Caledonia", flag: "🇳🇨" },
  { iso3: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { iso3: "NIC", name: "Nicaragua", flag: "🇳🇮" },
  { iso3: "NER", name: "Niger", flag: "🇳🇪" },
  { iso3: "NGA", name: "Nigeria", flag: "🇳🇬" },
  { iso3: "NIU", name: "Niue", flag: "🇳🇺" },
  { iso3: "NFK", name: "Norfolk Island", flag: "🇳🇫" },
  { iso3: "MKD", name: "North Macedonia", flag: "🇲🇰" },
  { iso3: "MNP", name: "Northern Mariana Islands", flag: "🇲🇵" },
  { iso3: "NOR", name: "Norway", flag: "🇳🇴" },
  { iso3: "OMN", name: "Oman", flag: "🇴🇲" },
  { iso3: "PAK", name: "Pakistan", flag: "🇵🇰" },
  { iso3: "PLW", name: "Palau", flag: "🇵🇼" },
  { iso3: "PSE", name: "Palestine, State of", flag: "🇵🇸" },
  { iso3: "PAN", name: "Panama", flag: "🇵🇦" },
  { iso3: "PNG", name: "Papua New Guinea", flag: "🇵🇬" },
  { iso3: "PRY", name: "Paraguay", flag: "🇵🇾" },
  { iso3: "PER", name: "Peru", flag: "🇵🇪" },
  { iso3: "PHL", name: "Philippines", flag: "🇵🇭" },
  { iso3: "PCN", name: "Pitcairn", flag: "🇵🇳" },
  { iso3: "POL", name: "Poland", flag: "🇵🇱" },
  { iso3: "PRT", name: "Portugal", flag: "🇵🇹" },
  { iso3: "PRI", name: "Puerto Rico", flag: "🇵🇷" },
  { iso3: "QAT", name: "Qatar", flag: "🇶🇦" },
  { iso3: "REU", name: "Réunion", flag: "🇷🇪" },
  { iso3: "ROU", name: "Romania", flag: "🇷🇴" },
  { iso3: "RUS", name: "Russian Federation", flag: "🇷🇺" },
  { iso3: "RWA", name: "Rwanda", flag: "🇷🇼" },
  { iso3: "BLM", name: "Saint Barthélemy", flag: "🇧🇱" },
  {
    iso3: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "🇸🇭",
  },
  { iso3: "KNA", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { iso3: "LCA", name: "Saint Lucia", flag: "🇱🇨" },
  { iso3: "MAF", name: "Saint Martin (French part)", flag: "🇲🇫" },
  { iso3: "SPM", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { iso3: "VCT", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { iso3: "WSM", name: "Samoa", flag: "🇼🇸" },
  { iso3: "SMR", name: "San Marino", flag: "🇸🇲" },
  { iso3: "STP", name: "Sao Tome and Principe", flag: "🇸🇹" },
  { iso3: "SAU", name: "Saudi Arabia", flag: "🇸🇦" },
  { iso3: "SEN", name: "Senegal", flag: "🇸🇳" },
  { iso3: "SRB", name: "Serbia", flag: "🇷🇸" },
  { iso3: "SYC", name: "Seychelles", flag: "🇸🇨" },
  { iso3: "SLE", name: "Sierra Leone", flag: "🇸🇱" },
  { iso3: "SGP", name: "Singapore", flag: "🇸🇬" },
  { iso3: "SXM", name: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
  { iso3: "SVK", name: "Slovakia", flag: "🇸🇰" },
  { iso3: "SVN", name: "Slovenia", flag: "🇸🇮" },
  { iso3: "SLB", name: "Solomon Islands", flag: "🇸🇧" },
  { iso3: "SOM", name: "Somalia", flag: "🇸🇴" },
  { iso3: "ZAF", name: "South Africa", flag: "🇿🇦" },
  {
    iso3: "SGS",
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
  },
  { iso3: "SSD", name: "South Sudan", flag: "🇸🇸" },
  { iso3: "ESP", name: "Spain", flag: "🇪🇸" },
  { iso3: "LKA", name: "Sri Lanka", flag: "🇱🇰" },
  { iso3: "SDN", name: "Sudan", flag: "🇸🇩" },
  { iso3: "SUR", name: "Suriname", flag: "🇸🇷" },
  { iso3: "SJM", name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
  { iso3: "SWE", name: "Sweden", flag: "🇸🇪" },
  { iso3: "CHE", name: "Switzerland", flag: "🇨🇭" },
  { iso3: "SYR", name: "Syrian Arab Republic", flag: "🇸🇾" },
  { iso3: "TWN", name: "Taiwan, Province of China", flag: "🇹🇼" },
  { iso3: "TJK", name: "Tajikistan", flag: "🇹🇯" },
  { iso3: "TZA", name: "Tanzania, United Republic of", flag: "🇹🇿" },
  { iso3: "THA", name: "Thailand", flag: "🇹🇭" },
  { iso3: "TLS", name: "Timor-Leste", flag: "🇹🇱" },
  { iso3: "TGO", name: "Togo", flag: "🇹🇬" },
  { iso3: "TKL", name: "Tokelau", flag: "🇹🇰" },
  { iso3: "TON", name: "Tonga", flag: "🇹🇴" },
  { iso3: "TTO", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { iso3: "TUN", name: "Tunisia", flag: "🇹🇳" },
  { iso3: "TUR", name: "Turkey", flag: "🇹🇷" },
  { iso3: "TKM", name: "Turkmenistan", flag: "🇹🇲" },
  { iso3: "TCA", name: "Turks and Caicos Islands", flag: "🇹🇨" },
  { iso3: "TUV", name: "Tuvalu", flag: "🇹🇻" },
  { iso3: "UGA", name: "Uganda", flag: "🇺🇬" },
  { iso3: "UKR", name: "Ukraine", flag: "🇺🇦" },
  { iso3: "ARE", name: "United Arab Emirates", flag: "🇦🇪" },
  {
    iso3: "GBR",
    name: "United Kingdom of Great Britain and Northern Ireland",
    flag: "🇬🇧",
  },
  { iso3: "USA", name: "United States of America", flag: "🇺🇸" },
  { iso3: "UMI", name: "United States Minor Outlying Islands", flag: "🇺🇲" },
  { iso3: "URY", name: "Uruguay", flag: "🇺🇾" },
  { iso3: "UZB", name: "Uzbekistan", flag: "🇺🇿" },
  { iso3: "VUT", name: "Vanuatu", flag: "🇻🇺" },
  { iso3: "VEN", name: "Venezuela (Bolivarian Republic of)", flag: "🇻🇪" },
  { iso3: "VNM", name: "Viet Nam", flag: "🇻🇳" },
  { iso3: "VGB", name: "Virgin Islands (British)", flag: "🇻🇬" },
  { iso3: "VIR", name: "Virgin Islands (U.S.)", flag: "🇻🇮" },
  { iso3: "WLF", name: "Wallis and Futuna", flag: "🇼🇫" },
  { iso3: "ESH", name: "Western Sahara", flag: "🇪🇭" },
  { iso3: "YEM", name: "Yemen", flag: "🇾🇪" },
  { iso3: "ZMB", name: "Zambia", flag: "🇿🇲" },
  { iso3: "ZWE", name: "Zimbabwe", flag: "🇿🇼" },
];

export default countries;
